# http://itstory.tk/entry/thymeleaf-legacy-html5-모드-설정#recentComments
spring:
  thymeleaf.mode: LEGACYHTML5
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2.console:
    enabled: true
    path: /h2-console